#!/bin/bash
# Include this file to ~/.bashrc

# User binaries
export PATH="$HOME/.local/bin:$PATH"

# Load custom Bash configuration
for config in "$HOME/.bash/"*.sh; do
    [[ -r "$config" ]] && source "$config"
done

export ZSH_LIKE_BASH_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
